# Generated by Django 3.1.1 on 2020-09-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.IntegerField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('pincode', models.CharField(max_length=6)),
            ],
        ),
    ]
