# Generated by Django 3.1.1 on 2020-11-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_complaintregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='crimestories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Heading', models.CharField(max_length=500)),
                ('detail', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='missingperson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=200)),
                ('age', models.IntegerField(max_length=3)),
                ('missing_date', models.DateField()),
                ('image', models.ImageField(default='', upload_to='app/images')),
            ],
        ),
        migrations.AlterField(
            model_name='complaintregister',
            name='house_no',
            field=models.IntegerField(max_length=4),
        ),
    ]
