# Generated by Django 3.1.1 on 2020-11-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20201115_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaintregister',
            old_name='sex',
            new_name='Gender',
        ),
        migrations.AlterField(
            model_name='complaintregister',
            name='distict_place',
            field=models.CharField(choices=[('Agra', 'Agra'), ('Aligarh', 'Aligarh'), ('\tAllahabad', 'Allahabad'), ('Azamgarh', 'Azamgarh'), ('Chitrakoot', 'Chitrakoot'), ('Faizabad', 'Faizabad'), ('Gorakhpur', 'Gorakhpur'), ('Jhansi', 'Jhansi'), ('Kanpur ', 'Kanpur '), ('Lucknow', 'Lucknow'), ('Meerut', 'Meerut'), ('Mirzapur', 'Mirzapur'), ('Moradabad', 'Moradabad'), ('Varanasi', 'Varanasi'), ('Etawah', 'Etawah'), ('Ghaziabad\t', 'Ghaziabad\t'), ('Jaunpur', 'Jaunpur'), ('Kasganj', 'Kasganj'), ('Farrukhabad', 'Farrukhabad'), ('Shahdara', 'Shahdara'), ('\tCentral Delhi', 'Central Delhi'), ('New Delhi ', 'New Delhi '), ('South Delhi', 'South Delhi'), ('South West Delhi', 'South West Delhi'), ('Bareilly', 'Bareilly')], max_length=100),
        ),
    ]
