# Generated by Django 3.1.1 on 2020-11-18 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20201118_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaintregister',
            old_name='Gender',
            new_name='gender',
        ),
    ]
