# Generated by Django 3.1.1 on 2020-11-22 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_auto_20201122_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userotp',
            old_name='user',
            new_name='user_name',
        ),
    ]
