# Generated by Django 3.1.1 on 2020-11-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_auto_20201122_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintregister',
            name='complaint_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='complaintregister',
            name='distict_place',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='complaintregister',
            name='gender',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='complaintregister',
            name='house_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='complaintregister',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
