# Generated by Django 3.1.1 on 2021-02-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_complaintregister_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaintregister',
            name='username',
        ),
        migrations.AddField(
            model_name='complaintregister',
            name='user',
            field=models.CharField(default='', max_length=100),
        ),
    ]
