# Generated by Django 3.1.1 on 2021-02-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_auto_20210208_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintregister',
            name='user',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
