# Generated by Django 3.1.1 on 2021-02-08 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_auto_20210208_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaintregister',
            old_name='user',
            new_name='name',
        ),
    ]
