# Generated by Django 3.1.1 on 2021-02-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_auto_20210208_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintregister',
            name='name',
            field=models.CharField(default=' ', max_length=100, null=True),
        ),
    ]
