# Generated by Django 3.1.1 on 2021-02-08 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_auto_20210208_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaintregister',
            name='name',
        ),
    ]
